#day_07
y = 1
while y > 0:
    print("#problem_statment_07!!")
    input_str_user = input("Enter The String: ")
    input_str = input_str_user.upper()
    # print(input_str)
    str_row = "ASSERTIVENESSLJCFOGOODPOSITIVEOPENBMUREWOPRPSMEDIATIONELDIOGMAASREGJEWINWINUCIAEMOEECSKENINEMRSHACDVTWTTLITEHOTLTSTERAOECASPLGLSIUNERFEAISAUSYTPOISEVFTTARTTDOCENPPIHIOGAIGUPYMGOOEEOGEPOAFPQIENOWANECONFLICTSDCERFNHTCATNOCEYEBT"
    str_column = "ACOMMUNICATIONFSFPEACETAITOGENSOEDAIMESSAGECHEGNISARHPARAPOTROBARESOLUTIONCTOMTEMHTGSTGAFAALLYDUFLTCTSTOPPINDSIPCYQCONSWEWCVTUOEMITCEIOLISTENINGESSESTPDNKWRESPONDYSIRIWETAREPOOCESIRIWETAREPOOCELVPOINTOFVIEWEVJESGNILEEFHEART"

    if input_str in str_row:
        print("Found")
        
    elif input_str in str_column:
        print("Found")
        
    else:
        print("Not Found")